### ISSUE TITLE
Epic: execute jitted code for all remaining branches

### ISSUE THREAD

**Issue by Fidget-Spinner** [pylbbv/pylbbv#71]
- [x] All variants of BB_BRANCH
- [x] All variants of BB_JUMP
- [x] JUMP_BACKWARD (likely the most difficult one to do)
